# Generated by Django 5.2.9 on 2026-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_pharmac_31e087_idx',
            old_name='inventory_b_pharmac_389ecc_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_pharmac_6150bc_idx',
            old_name='inventory_b_pharmac_461579_idx',
        ),
        migrations.RenameIndex(
            model_name='catalogmedicine',
            new_name='inventory_c_brand_n_4cb803_idx',
            old_name='inventory_c_brand_n_6d68b4_idx',
        ),
        migrations.RenameIndex(
            model_name='catalogmedicine',
            new_name='inventory_c_generic_51b613_idx',
            old_name='inventory_c_generic_9dd376_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_pharmac_69ac9a_idx',
            old_name='inventory_m_pharmac_97fe31_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_pharmac_baca63_idx',
            old_name='inventory_m_pharmac_c50663_idx',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
