# Generated by Django 5.2.9 on 2026-09-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_b_pharmac_389ecc_idx_inventory_b_pharmac_31e087_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_token', models.CharField(db_index=True, max_length=512)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('succeeded', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='inventory.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=16)),
                ('source', models.CharField(choices=[('none', 'None'), ('trial', 'Trial'), ('play', 'Google Play'), ('web', 'Web'), ('manual', 'Manual')], default='none', max_length=16)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('purchase_token', models.CharField(blank=True, db_index=True, max_length=512)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('auto_renewing', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='inventory.pharmacy')),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'valid_until'], name='inventory_s_plan_0ead04_idx')],
            },
        ),
    ]
