# Generated by Django 5.2.9 on 2026-09-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_signupdailycount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date', 'received_at', 'id'], 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'pharmacies'},
        ),
    ]
