# Generated by Django 5.2.9 on 2026-09-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_signupdailycount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signupdailycount',
            new_name='inventory_s_ip_4b8eb0_idx',
            old_name='inventory_si_ip_day_idx',
        ),
        migrations.RenameIndex(
            model_name='signuprequest',
            new_name='inventory_s_status_2e433b_idx',
            old_name='inventory_si_status_2e3e1c_idx',
        ),
    ]
