# Generated by Django 5.2.9 on 2026-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_batch_options_alter_pharmacy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyapikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=16),
        ),
    ]
