# Generated by Django 5.2.9 on 2026-10-06 15:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_pharmacyapikey_expires_at_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('owner', 'Owner')], default='staff', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['organization', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('owner', 'Owner')], default='staff', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_send_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='branch_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('bin', models.CharField(blank=True, max_length=32, verbose_name='BIN / VAT registration')),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('locale', models.CharField(default='bn', max_length=8)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('free', 'Free'), ('branch', 'Branch plan'), ('enterprise', 'Enterprise')], default='trial', max_length=16)),
                ('branch_allowance', models.PositiveIntegerField(default=1)),
                ('seat_addon_count', models.PositiveIntegerField(default=0)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('brand_color', models.CharField(blank=True, max_length=9)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('white_label_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['slug'], name='inventory_o_slug_a2e180_idx'), models.Index(fields=['plan', 'is_active'], name='inventory_o_plan_8f657b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('login_failed', 'Login failed'), ('invite', 'Invite'), ('invite_accepted', 'Invitation accepted'), ('role_changed', 'Role changed'), ('seat_limit_reached', 'Seat limit reached'), ('plan_changed', 'Plan changed'), ('export', 'Export'), ('api_key_issued', 'API key issued'), ('api_key_revoked', 'API key revoked'), ('payment_recorded', 'Payment recorded')], max_length=24)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='inventory.pharmacy')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='inventory.organization')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='inventory.organization'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_p_organiz_dc7520_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.UniqueConstraint(condition=models.Q(('branch_code__gt', '')), fields=('organization', 'branch_code'), name='unique_branch_code_per_organization'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='default_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_memberships', to='inventory.pharmacy'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to='inventory.orgmembership'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inventory.organization'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='scoped_pharmacies',
            field=models.ManyToManyField(blank=True, related_name='scoped_memberships', to='inventory.pharmacy'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='default_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='inventory.pharmacy'),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='inventory.orgmembership'),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='inventory.organization'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='inventory_a_organiz_dc3fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['pharmacy', '-created_at'], name='inventory_a_pharmac_01eaab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='inventory_a_action_4c2c92_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='inventory_a_target__45ff32_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmembership',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_o_organiz_892a84_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmembership',
            index=models.Index(fields=['user', 'is_active'], name='inventory_o_user_id_122c27_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_membership_per_org_user'),
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_92c32f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['email', 'status'], name='inventory_s_email_26cdbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invitation_per_email'),
        ),
    ]
