# Generated by Django 5.2.9 on 2026-10-06 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_orgmembership_staffinvitation_pharmacy_branch_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(db_index=True, max_length=32, unique=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("issued", "Issued"), ("paid", "Paid"), ("void", "Void")], db_index=True, default="draft", max_length=8)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("seller_name", models.CharField(blank=True, max_length=255)),
                ("seller_bin", models.CharField(blank=True, max_length=32)),
                ("buyer_name", models.CharField(blank=True, max_length=255)),
                ("buyer_bin", models.CharField(blank=True, max_length=32)),
                ("buyer_address", models.CharField(blank=True, max_length=255)),
                ("subtotal", models.PositiveIntegerField(default=0)),
                ("vat_percent", models.CharField(default="15.00", max_length=8)),
                ("vat_amount", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("plan", models.CharField(blank=True, max_length=16)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="inventory.organization")),
            ],
            options={
                "ordering": ["-period_start", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("base", "Base plan"), ("branch", "Additional branch"), ("seat", "Additional seat"), ("addon", "Add-on")], default="branch", max_length=12)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount", models.PositiveIntegerField(default=0)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("pharmacy_id", models.UUIDField(blank=True, null=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.invoice")),
            ],
            options={
                "ordering": ["kind", "description", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["organization", "status"], name="inventory_i_organiz_dd0558_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status", "-period_start"], name="inventory_i_status_57d17c_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "void"), _negated=True), fields=("organization", "period_start", "period_end"), name="unique_live_invoice_per_period"),
        ),
    ]
