# Generated by Django 5.2.17 on 2026-10-08 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AggregatedInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=32)),
                ('area', models.CharField(blank=True, db_index=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shop_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-period', 'area', 'metric'],
                'indexes': [models.Index(fields=['metric', 'period'], name='inventory_a_metric_6184eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'area', 'category', 'metric'), name='unique_insight_cell'), models.CheckConstraint(condition=models.Q(('shop_count__gte', 10)), name='insight_min_group_10')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonymous_id', models.CharField(db_index=True, max_length=40)),
                ('event_name', models.CharField(max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['event_name', 'ts'], name='inventory_a_event_n_71e487_idx'), models.Index(fields=['pseudonymous_id', 'ts'], name='inventory_a_pseudon_982c9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_wholesalers', models.JSONField(blank=True, default=list)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='inventory.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, db_index=True, max_length=80)),
                ('upazila', models.CharField(blank=True, max_length=80)),
                ('shop_type', models.CharField(blank=True, choices=[('retail', 'Retail pharmacy'), ('wholesale', 'Wholesale'), ('clinic', 'Clinic or hospital pharmacy'), ('other', 'Other')], max_length=16)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('pharmacist', 'Pharmacist'), ('staff', 'Staff')], max_length=16)),
                ('size_range', models.CharField(blank=True, choices=[('under_100', 'Under 100 items'), ('100_500', '100 to 500 items'), ('500_2000', '500 to 2000 items'), ('over_2000', 'Over 2000 items')], max_length=16)),
                ('license_no_encrypted', models.TextField(blank=True)),
                ('profile_completeness', models.PositiveSmallIntegerField(default=0)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='inventory.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('analytics', 'Anonymous usage statistics'), ('sponsor_offers', 'Offers from distributors'), ('area_insights', 'Area-level market insights')], max_length=24)),
                ('granted', models.BooleanField(default=False)),
                ('policy_version', models.CharField(blank=True, max_length=16)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='inventory.pharmacy')),
            ],
            options={
                'ordering': ['type'],
                'indexes': [models.Index(fields=['pharmacy', 'type'], name='inventory_u_pharmac_4006c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'type'), name='unique_consent_per_pharmacy')],
            },
        ),
    ]
